# Generated by Django 2.1.5 on 2019-02-21 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete='cascade', primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_picture', models.ImageField(blank=True, null=True, upload_to='media')),
                ('user_balance', models.IntegerField(default=0)),
            ],
        ),
    ]
