# Generated by Django 2.1.5 on 2019-02-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190124_2056'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='profiles.UserProfile'),
        ),
    ]
