# Generated by Django 2.1.2 on 2018-12-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='mem_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
