# Generated by Django 2.1.5 on 2019-02-24 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_mem_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
