# Generated by Django 2.1.2 on 2018-12-21 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181221_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam', to=settings.AUTH_USER_MODEL),
        ),
    ]
