# Generated by Django 2.1.5 on 2019-01-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190127_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
