# Generated by Django 2.1.5 on 2019-01-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_mem_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='available',
            field=models.BooleanField(),
        ),
    ]
