# Generated by Django 2.1.5 on 2019-01-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190131_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
