# Generated by Django 2.1.5 on 2019-02-10 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190124_2056'),
        ('shop', '0009_auto_20190131_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='mem_profile',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam', to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile'),
        ),
    ]
