# Generated by Django 2.1.5 on 2019-02-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190210_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mem',
            name='mem_profile',
        ),
    ]
