# Generated by Django 2.1.5 on 2019-02-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20190211_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mems_of_profile', to='profiles.UserProfile'),
        ),
    ]
