# Generated by Django 2.1.5 on 2019-02-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20190211_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem', to='shop.Category'),
        ),
    ]
